version: '3.8'

services:
  sveltekit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - ./development.db:/app/development.db
    restart: always

volumes:
  sqlite-db:
